version: '3.7'

volumes:
  postgres_data:
    driver: local

services:

  ff-user-service:
    image: docker.pkg.github.com/fellow-flow/user-service/ff-user-service:latest
    ports:
      - "8090:8090"
    restart: always
    depends_on:
      usu-keycloak:
        condition: service_healthy

  ff-keycloak:
    restart: always
    image: jboss/keycloak:12.0.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: ff-keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "curl -v http://localhost:8080/auth"]
      interval: 10s
      timeout: 5s
      retries: 50
    ports:
      - "3000:8080"

  ff-keycloak-db:
    image: postgres:11-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    expose:
      - 5432

  ff-mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
